### ISSUE TITLE
"Error: connect ECONNREFUSED" when web-layer isn't running

### ISSUE THREAD

**Issue by andrewazores** [Anirudh94/boreas#20]
As described by Jie in a PR comment:

"""
I tested it without running the underlying storage api running and when a client visits the site, the server crashes:

events.js:141
throw er; // Unhandled 'error' event
^

Error: connect ECONNREFUSED 127.0.0.1:8080
at Object.exports._errnoException (util.js:907:11)
at exports._exceptionWithHostPort (util.js:930:20)
at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

Could you handle this case as well? Either display no data, or display an error page. The server should still run and later, if the backend layer starts running, and a client visits the page again, it would work.
"""

I see this happening however when doing "npm start" in boreas/server when the boreas/web-layer is not running ("mvn exec:java"), with there not even being an opportunity for the server to come up let alone a client to visit.

Is the right fix here to have the server come up but display some error message to client connections? Or should the server perhaps just fail with a more informative error message that a key component of the backend is missing? The case where the Thermostat web-storage-service goes away is already handled relatively gracefully - it's just if boreas/web-layer is missing that this occurs.

**Comment by andrewazores** [comment]
Whoops, actually, I made a mistake - I didn't realize I still had a client tab open elsewhere in my browser. So in fact the initial report was correct and the exception is not thrown unless a client attempts to connect. Either we should detect the missing web-layer sooner and have the server fail faster, or show a message to the client (or both).

**Comment by andrewazores** [comment]
Initial handling is implemented. Should probably have a prettier message to display on the client side, but it's handled gracefully rather than crashing anyway.
